### PR TITLE
Add a simple viewing script to visualize the obj meshes and segmentation information

### PR DESCRIPTION
**Pull request by JoeLambourne**
# Why?
We need tools to visualize the segmentation dataset.  The tooling using the forge platform requires a special extractor.

# What?

Add a simple viewer script which can visualize the obj meshes and segmentation information.

### CODE REVIEW

**Comment by karldd** [comment]
Excellent. This will be very useful.

Minor suggestion: Would it be possible to add an image of what the expected visualization output is to the readme?
I find it is easy to upload the image to [gyazo.com](https://gyazo.com) (or similar) rather than fill up the repo with images. And then include it like this:
```
<img src="https://i.gyazo.com/2e3ad713965f5dea85ccaa6681fe7886.png" width="400" alt="Regraph">
```

**Comment by karldd** [comment]
@JoeLambourne I managed to run the script. I updated the readme to list the requirements. I had to install `pyglet`.
This is what I am seeing, with what looks like some odd color smoothing going on. Is this what you see too?

image

**Comment by JoeLambourne** [comment]
It looks like it doesn't work in a notebook
https://github.com/mikedh/trimesh/issues/226

**Comment by karldd** [comment]
The screenshot above is not from a notebook, but from running the script as is.

**Comment by karldd** [comment]
Thanks for fixing this. I added an example image and fixed a few typos. Will merge.

**Pull request merged**
